language: go
sudo: required
services:
  - docker
go:
  - 1.8
install:
  - (cd test && docker-compose up -d)
  - docker pull yandex/clickhouse-client
  - sudo apt-get update -qq
  - sudo apt-get install -y libpcap0.8 libpcap0.8-dev libnuma-dev
script:
  - cat tables.sql | docker run -i -a stdin --rm --net=host yandex/clickhouse-client --multiquery
  - go test .
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
