version: '2'
services:
  clickhouse:
    build: ./clickhouse
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - clickhouse_volume:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  grafana:
    build: ./grafana
    ports:
      - 3000:3000
  godnscaptureclickhouse:
    build:
      context: ../
      dockerfile: docker/godnscaptureclickhouse/Dockerfile
      args:
        - dev=lo
    network_mode: host
volumes:
  clickhouse_volume:
    driver: local
